// Toyin-Olanipekun-Id_063_FrtendMd3/vue/src/components/AddContact.vue
<template>
  <form @submit="onSubmit" class="add-form">
    <div class="form-control">
      <label>Name</label>
      <input type="text" v-model="name" placeholder="Add Full Name" required />
    </div>
    <div class="form-control">
      <label>Phone Number</label>
      <input
        type="text"
        v-model="phone"
        placeholder="Add Phone Number"
        required
      />
    </div>

    <input type="submit" value="Save Contact" className="btn btn-block" />
  </form>
</template>



<script>
export default {
  name: "AddContact",
  data() {
    return {
      name: "",
      phone: "",
    };
  },
  methods: {
    onSubmit(e) {
      e.preventDefault();
      const newContact = {
        id: Math.floor(Math.random() * 100000),
        name: this.name,
        phone: this.phone,
      };

      this.$emit("add-contact", newContact);

      this.name = "";
      this.phone = "";
    },
  },
};
</script>
<style scoped>
</style>

// Toyin-Olanipekun-Id_063_FrtendMd3/angular/src/app/component/add-contact/add-contact.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Contact } from 'src/app/Contact';

@Component({
  selector: 'app-add-contact',
  templateUrl: './add-contact.component.html',
  styleUrls: ['./add-contact.component.css']
})
export class AddContactComponent implements OnInit {
  @Output() onAddContact: EventEmitter<Contact> = new EventEmitter

  name!: string;
  phone!: string;

  constructor() { }

  ngOnInit(): void {
  }
  onSubmit() {
    const newContact = {
      name: this.name,
      phone: this.phone
    };

    this.onAddContact.emit(newContact)

    this.name = '';
    this.phone = '';
  }
}

<form class="add-form" (ngSubmit)="onSubmit()">
    <div class="form-control ">
        <label for="name">Name</label>
        <input type="text" name="name" [(ngModel)]="name" id="name" placeholder="type name..." required />
    </div>
    <div class="form-control">
        <label for="phone">Phone Number</label>
        <input type="text" name="phone" [(ngModel)]="phone" id="phone" placeholder="type phone number..." required />
    </div>

    <input type="submit" value="Save Contact" class="btn btn-block" />
</form>
